### ISSUE TITLE
Make repo private

### ISSUE THREAD

**Issue by lollofra** [MarcoBuster/OrarioTreniBot#16]
**Don't program open source**, you are helping the spread of communism for the god sake!
![5c3vz8kmt9j01](https://user-images.githubusercontent.com/17254822/106732368-ead0e280-6610-11eb-961d-e5231b971f4a.jpg)

**Comment by Knocks83** [comment]
@lollofra It's OUR program now

**Comment by MarcoBuster** [comment]
LOL
